# Generated by Django 4.1 on 2022-08-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('photo', models.ImageField(null=True, upload_to='employee_images')),
            ],
        ),
    ]
